### PR TITLE
Added flexbox to code snippet

### PR DESCRIPTION
**Pull request by sampoonachot**
### Old Code Snippet
screen shot 2018-08-06 at 11 33 37 am

### New Code Snippet
* added flexbox so text doesn't extend past the button
* changed button styling to `btn-default` instead of `btn-info` to be consistent with the code snippet on Cloud, Stitch and Charts

compass-copy-snippet

### CODE REVIEW

**Comment by aherlihy** [comment]
@sampoonachot If you have a longer document, will the lower lines extend past where the button is or will it stop at the same place the whole way down? So is the space under the copy button always going to be empty?

**Comment by durran** [comment]
Why not just move the copy button up next to the target language dropdown?

**Comment by sampoonachot** [comment]
### New Design
option a
aug-08-2018 15-53-06

**Comment by sampoonachot** [comment]
@durran not exactly sure why tests are failing.. I tried to run `nvm install 8.2.1 && nv alias default 8.2.1` and then commit that but it says it's skipping the pre-commit hook. Not sure if it is an nvm install issue anyways?

**Comment by sampoonachot** [comment]
require npm 5.4?

**Comment by lrlna** [comment]
@sampoonachot there are just a few issues with travis on this one with CI tests. If you want I can fix those up and push to this PR?

**Comment by sampoonachot** [comment]
@lrlna that'd be really helpful, thank you!!

**Pull request merged**
